### ISSUE TITLE
Why not use English as the comment language?

### ISSUE THREAD

**Issue by dlee992** [kusumotolab/kGenProg#699]
Thanks for your commitment in this repository.

However, I'm a Chinese, I want to read and learn the source code of this repository, but all comments are Japanese. It's unfriendly for me... How about providing a version with English comments?

Maybe, this is an unfriendly issue for you, sry...

**Comment by YoshikiHigo** [comment]
Thank you for your feedback.
We have already made a discussion about writing code comments in English.
We, of course, know that English comments are better than Japanese ones for users.
But, at this moment, due to internal reasons, we are using Japanese for code comment.
In the future, we may transrate code comments to English or write them in the two languages.

**Comment by dlee992** [comment]
@YoshikiHigo Thanks!
